--Depo Bazlý Bakiye Listesi
select a.DEPO_KODU,A.STOK_KODU,DBO.TRK(B.STOK_ADI) AS STOK_ADI, CONVERT(DECIMAL(18,6),SUM(case when A.sthar_gckod='G' then A.STHAR_GCMIK else -A.STHAR_GCMIK end))  AS BAKIYE 
from TBLSTHAR A
LEFT JOIN TBLSTSABIT B ON B.STOK_KODU=A.STOK_KODU
WHERE A.STHAR_TARIH < '2023-06-01'
GROUP BY A.DEPO_KODU,A.STOK_KODU,B.STOK_ADI
HAVING CONVERT(DECIMAL(18,6),SUM(case when A.sthar_gckod='G' then A.STHAR_GCMIK else -A.STHAR_GCMIK end))<0 
ORDER BY A.STOK_KODU

-- Toplam Bakiyeler
select A.STOK_KODU,DBO.TRK(B.STOK_ADI) AS STOK_ADI, CONVERT(DECIMAL(18,2),SUM(case when A.sthar_gckod='G' then A.STHAR_GCMIK else -A.STHAR_GCMIK end))  AS BAKIYE 
from TBLSTHAR A
LEFT JOIN TBLSTSABIT B ON B.STOK_KODU=A.STOK_KODU
WHERE A.STHAR_TARIH < '2023-05-01' M-P-0009-1-002-022
GROUP BY A.STOK_KODU,B.STOK_ADI
HAVING CONVERT(DECIMAL(18,2),SUM(case when A.sthar_gckod='G' then A.STHAR_GCMIK else -A.STHAR_GCMIK end))<0 
ORDER BY A.STOK_KODU

select a.DEPO_KODU,A.STOK_KODU,DBO.TRK(B.STOK_ADI) AS STOK_ADI, CONVERT(DECIMAL(18,6),SUM(case when A.sthar_gckod='G' then A.STHAR_GCMIK else -A.STHAR_GCMIK end))  AS BAKIYE 
from TBLSTHAR A
LEFT JOIN TBLSTSABIT B ON B.STOK_KODU=A.STOK_KODU
WHERE A.STHAR_TARIH < '2023-06-01' AND A.STOK_KODU='M-A-3022-1-093-130'
GROUP BY A.DEPO_KODU,A.STOK_KODU,B.STOK_ADI
ORDER BY A.STOK_KODU