SELECT A.STOK_KODU,Sum((A.STHAR_GCMIK)) as ToplamGirisMiktar,Sum((A.STHAR_GCMIK*A.STHAR_NF)) as ToplamGirisTutar
FROM TBLSTHAR A WHERE A.STHAR_GCKOD='G' AND A.STHAR_HTUR NOT IN ('B','A','C')  AND MONTH(A.STHAR_TARIH)=1 AND A.STOK_KODU LIKE 'H-%'
Group BY A.STOK_KODU

SELECT A.STOK_KODU,Sum((A.STHAR_GCMIK)) as ToplamDevirMiktar,Sum((A.STHAR_GCMIK*A.STHAR_NF)) as ToplamDevirTutar
FROM TBLSTHAR A WHERE A.STHAR_GCKOD='G' AND A.STHAR_HTUR NOT IN ('B','C') AND A.STHAR_HTUR='A'  AND MONTH(A.STHAR_TARIH)=1 AND A.STOK_KODU LIKE 'H-%'
Group BY A.STOK_KODU
